### ISSUE TITLE
missing command 'tree' (when running nanoasv --mock)

### ISSUE THREAD

**Issue by frederic-mahe** [ImagoXV/NanoASV#108]
`tree` is not installed by default:

``` text
/home/fred/NanoASV/workflow/run.sh: line 297: tree: command not found
```

Either add it to the list of dependencies, or install it in the conda
environment?

**Comment by ImagoXV** [comment]
Yes, it's corrected thank you 

19d0772e15a542f00e8e5d628f561a63bf95afb9
