### ISSUE TITLE
use vsearch option to eliminate a call to awk

### ISSUE THREAD

**Issue by frederic-mahe** [ImagoXV/NanoASV#70]
https://github.com/ImagoXV/NanoASV/blob/79f3132d9776420142cf8f288582d0d5560ddf92/script.sh#L428

with the option `--fasta_width 0`, vsearch produces unwrapped/unfolded fasta files.

**Comment by ImagoXV** [comment]
Thank you very much Fred. 

It's done 

https://github.com/ImagoXV/NanoASV/commit/44734545c46e432020c31dc7d396dea989af8271
