### ISSUE TITLE
Urgently needed modifications

### ISSUE THREAD

**Issue by ImagoXV** [ImagoXV/NanoASV#72]
List of needed features and modifications

- [x] Personal database implementation
     https://github.com/ImagoXV/NanoASV/commit/a48298e33ebc8c7b62db2f117e6a6d5e207543f7 - Personal database OK. Indexing step at first NanoASV run
- [x] Change the moment when the database is indexed. Need to write on computer outside of container
     https://github.com/ImagoXV/NanoASV/commit/9a1bdec48ac0f3c1ef484af6e023d6d248a9a9fd - SILVA is no longer indexed at building step
- [x] Rewrite samtools filtering process. Remove bash language to let samtools do the job. 
     https://github.com/ImagoXV/NanoASV/commit/427cfc05db14844528eeb4921a5549b496196d38 - Samtools does a proper filtering job now without parsing sam files with grep. I wonder if indexing step is usefull or not
- [x] Make installation process more user friendly
     Should be handled quite well with uploading a singularity image file (SIF) executable as release. No more building from source with docker !
- [x] Make more comparison with Nyygaard pipeline
- [x] Run published data with NanoASV and compare composition dataset for example

Additional fixes or changes:
- [x] update to Silva 138.2,
- [x] fix indentation throughout `script.sh`,
- [x] eliminate intermediate or temporary files as soon as possible,
- [x] remove all commented code,
- [x] replace paths such as `/opt/` with a variable (easier to modify),
- [ ] put DEBUG code behind a test: `[[ ${DEBUG} == "TRUE" ]] && { code ;}`
- [ ] in the bash script, is there an alternative to declaring `env` variables for `parallel`?
- [x] in R, add package names to function that are not R-base (e.g.; `dplyr::mget()`) to make it easier to understand the origin of each function and the role of each package

**Comment by frederic-mahe** [comment]
Personal database: you should document somewhere the exact format required by your pipeline. You should also set up basic tests to check if the database provided by the user is ok before running with it.

**Comment by ImagoXV** [comment]
Yes that's a excellent point. It will need some work

Notably, Taxonomy is extracted from the fasta file. It is relevant for Silva or GreenGenes, but needs a lot of conditions if a regular fasta file is loaded
At this point the only real test and homogeneization is the automatic transformation from a multiple line to a single line fasta file

**Comment by frederic-mahe** [comment]
I've made a list of suggestions after reading your recent commits.

**Comment by ImagoXV** [comment]
Salut Fred, comment vas tu ? 

Merci pour tes commits ! 

Tu n'étais pas en vacances en Bretagne ? 

je suis à EBAME pour ces deux semaines ;) 

Bonne journée ! 

Arthur 


De: "Frédéric Mahé" ***@***.***> 
À: "ImagoXV/NanoASV" ***@***.***> 
Cc: "arthur cousson" ***@***.***>, "Author" ***@***.***> 
Envoyé: Lundi 14 Octobre 2024 19:15:23 
Objet: Re: [ImagoXV/NanoASV] Urgently needed modifications (Issue #72) 





I've made a list of suggestions after reading your recent commits.

**Comment by ImagoXV** [comment]
Thank you very much Fred, I'll dive into it
