### ISSUE TITLE
Unknown sequences clustering refactoring

### ISSUE THREAD

**Issue by ImagoXV** [ImagoXV/NanoASV#81]
Better use of vsearch is needed to manipulate clusters

**Comment by frederic-mahe** [comment]
first attempt in commit https://github.com/ImagoXV/NanoASV/commit/944ff5db9f18ee677a49c2688dc6936846f3a8e4

Let me know if it works.

**Comment by ImagoXV** [comment]
It works as intended, but I wish we discuss about unknown sequences handling a little more.
